---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourceSvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.resourceSvc.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.resourceSvc.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.resourceSvc.name }}
    spec:
      containers:
        - name: {{ .Values.resourceSvc.name }}
          image: irrisorrimus/{{ .Values.resourceSvc.name }}:{{ .Values.songSvc.tag }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: {{ .Values.resourceSvc.name }}-db-secret
            - configMapRef:
                name: app-deployment-config
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/{{ .Values.resourceSvc.name }}/health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/{{ .Values.resourceSvc.name }}/health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/{{ .Values.resourceSvc.name }}/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
