---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.songSvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.songSvc.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.songSvc.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.songSvc.name }}
    spec:
      containers:
        - name: {{ .Values.songSvc.name }}
          image: irrisorrimus/{{ .Values.songSvc.name }}:{{ .Values.songSvc.tag }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: {{ .Values.songSvc.name }}-db-secret
          env:
            - name: SONG_SVC_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-deployment-config
                  key: SONG_SVC_PORT
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/{{ .Values.songSvc.name }}/health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/{{ .Values.songSvc.name }}/health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/{{ .Values.songSvc.name }}/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
