---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.songSvc.name }}-health-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /actuator/{{ .Values.songSvc.name }}/health
            pathType: Exact
            backend:
              service:
                name: {{ .Values.songSvc.name }}
                port:
                  number: 8080
